config/routes.rb
Rails.application.routes.draw do

  get "relationships/followings"
  get "relationships/followers"
  devise_for :users
  root to: "homes#top"
  get "/homes/about" => "homes#about"
  get "/homes/my_calender" => "homes#my_calender"
  get "/bookmarks" => "bookmarks#index"
  post "/homes/guest_sign_in", to: "homes#new_guest"

  resources :declutters do
    resources :declutter_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end

  resources :users, only:[:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :user
  belongs_to :declutter

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:create, :destroy]

  def  index
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end

  def create
    @bookmark = @declutter.bookmarks.new(user_id: current_user.id)
    @bookmark.save
    # render先にjsファイルを指定
    render :bookmarks
  end

  def destroy
    @bookmark = @declutter.bookmarks.find_by(user_id: current_user.id)
    @bookmark.destroy
    # render先にjsファイルを指定
    render :bookmarks
  end

  private

  def set_bookmark
    @declutter = Declutter.find(params[:declutter_id])
  end

end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bookmark-btn.html.slim
- if declutter.bookmarked_by?(current_user)
  = link_to declutter.bookmarks.count,declutter_bookmarks_path(declutter), method: :delete, remote: true, class: "fas fa-bookmark text-muted"
- else
  = link_to declutter.bookmarks.count,declutter_bookmarks_path(declutter), method: :post, remote: true, class: "far fa-bookmark text-muted"

app/views/bookmarks/bookmarks.js.erb
$("#bookmark_btn<%= @declutter.id %>").html("<%= j(render 'bookmarks/bookmark-btn', declutter: @declutter) %>");

app/views/bookmarks/index.html.slim
.container.mt-5.bookmarks_group
  h2.form_title
    | ブックマーク一覧
  .row
    - @bookmarks.each do |bookmark|
      .col-md-3.mt-5
        .card.card-height[style="width: 100%;"]
          = link_to declutter_path(bookmark.declutter) do
            = attachment_image_tag bookmark.declutter, :thing_image, class: "card-img-top-height"
          .card-body
              .row.card-link
                p
                  = link_to"#{bookmark.declutter.declutter_comments.count}", declutter_path(bookmark.declutter.id), class: "far fa-comment text-muted"
                | <div id="like_btn_
                = bookmark.declutter.id
                | ">
                = render "likes/like-btn", declutter: bookmark.declutter
                | </div>
                p
                  = render "bookmarks/bookmark-btn", declutter: bookmark.declutter
              h4.card-title.text-center
                = bookmark.declutter.title
              .card-text.text-right
                = link_to user_path(bookmark.declutter.user.id) do
                  = bookmark.declutter.user.name
                  = attachment_image_tag bookmark.declutter.user, :profile_image, :fill, 40, 40, fallback: asset_path("no_image.jpg"), size:"40x40", class: "rounded-circle ml-2"
              .card-text.text-right.text-muted.mt-1.small
                = time_ago_in_words(bookmark.created_at)
                | 前