config/routes.rb
Rails.application.routes.draw do

  get "relationships/followings"
  get "relationships/followers"
  devise_for :users
  root to: "homes#top"
  get "/homes/about" => "homes#about"
  get "/homes/my_calender" => "homes#my_calender"
  get "/bookmarks" => "bookmarks#index"
  post "/homes/guest_sign_in", to: "homes#new_guest"

  resources :declutters do
    resources :declutter_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end

  resources :users, only:[:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :declutters, dependent: :destroy
  has_many :declutter_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  # フォローする・されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロー・フォロワー一覧画面
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローをしているかどうかを確認
  def following?(user)
    followings.include?(user)
  end

  attachment :profile_image
  
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 10}
  validates :introduction, length: { maximum: 50 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @declutters = @user.declutters.page(params[:page]).reverse_order.per(6)
  end

  def edit
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice]="プロフィールが更新されました"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.slim
= attachment_image_tag user, :profile_image, :fill,250,250, format:"jpeg", fallback: asset_path("no_image.jpg"), size:"250x250", class:"rounded-circle"
h3
  = user.name
  | 　Lv.
  = user.level
h5
  = user.introduction
p
  = link_to user.followings.count, user_followings_path(user)
  | フォロー中・
  = link_to user.followers.count, user_followers_path(user)
  | フォロワー

- if current_user != user
  - if current_user.following?(user)
    = link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-success"
  - else
    = link_to "フォロー", user_relationships_path(user.id), method: :post, class: "btn btn-outline-success"
- else
  = link_to "", edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-cog"
  .link_group
    = link_to "", bookmarks_path, class:"btn btn-{themecolor} rounded-circle p-3 fas fa-bookmark"
    = link_to "", new_declutter_path, class:"btn btn-{themecolor} rounded-circle p-3 fas fa-plus"
    = link_to "", homes_my_calender_path, class:"btn btn-{themecolor} rounded-circle p-3 far fa-calendar-alt"

app/views/users/edit.html.slim
.container.mt-5.user_edit_group
  .row
    .col-md-12
      h2.form_title
        | プロフィール編集
      = form_with model:@user, local:true do |f|
        .col-md-4.mx-auto
          .form-group.photo_img
            = attachment_image_tag @user, :profile_image, :fill,250,250, fallback: asset_path("no_image.jpg"), size:"250x250", class:"image-preview rounded-circle"
          .form-group.photo_choice_btn
            = f.attachment_field :profile_image, id:"file", class:"profile_image_btn"
            = render 'layouts/photo_btn', f: f
          .form-group
            = f.label:Name
            br
            = f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control"
            - if @user.errors.include?(:name)
              p.text-danger
                = @user.errors.full_messages_for(:name).first
          .form-group
            = f.label:Introduction
            br
            = f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介", class: "form-control"
            - if @user.errors.include?(:introduction)
              p.text-danger
                = @user.errors.full_messages_for(:introduction).first
          .actions.form_btn_group
            = f.submit "変更する", class:"form_btn"

app/views/users/index.html.slim
.container.mt-5
  h2.table_title
    | Users
  table.table
    - @users.each do |user|
      tbody
        tr
          td
            = link_to user_path(user.id) do
              = attachment_image_tag user, :profile_image, :fill,60,60, format:"jpeg", fallback:asset_path("no_image.jpg"), size:"60x60", class:"rounded-circle"
          td
            = user.name
          td
            | Lv.
            = user.level
          td
            = user.introduction
          td
            - if current_user != user
              - if current_user.following?(user)
                = link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-success"
              - else
                = link_to "フォロー", user_relationships_path(user.id), method: :post, class: "btn btn-outline-success"

app/views/users/show.html.slim
.container.mt-5.user_show_group
  .row
    .col-md-4.user_info
      = render 'users/sidebar', user: @user
    .col-md-8
      .row
        - @declutters.each do |declutter|
          .col-md-4.mt-3
            .card.card-height[style="width: 100%;"]
              = link_to declutter_path(declutter.id) do
                = attachment_image_tag declutter, :thing_image, class: "card-img"
              .card-body
                .row.card-link
                  p
                    = link_to"#{declutter.declutter_comments.count}", declutter_path(declutter.id), class: "far fa-comment text-muted"
                  | <div id="like_btn_
                  = declutter.id
                  | ">
                  = render "likes/like-btn", declutter: declutter
                  | </div>
                  p
                  | <div id="bookmark_btn
                  = declutter.id
                  | ">
                  = render "bookmarks/bookmark-btn", declutter: declutter
                  | </div>
                h5.card-title.text-center
                  = declutter.title
                .card-text.text-right.text-muted.mt-1.small
                  = time_ago_in_words(declutter.created_at)
                  | 前

      = paginate @declutters