config/routes.rb
Rails.application.routes.draw do

  get "relationships/followings"
  get "relationships/followers"
  devise_for :users
  root to: "homes#top"
  get "/homes/about" => "homes#about"
  get "/homes/my_calender" => "homes#my_calender"
  get "/bookmarks" => "bookmarks#index"
  post "/homes/guest_sign_in", to: "homes#new_guest"

  resources :declutters do
    resources :declutter_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end

  resources :users, only:[:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

app/models/declutter_comment.rb
class DeclutterComment < ApplicationRecord

  belongs_to :user
  belongs_to :declutter

end

app/controllers/declutter_comments_controller.rb
class DeclutterCommentsController < ApplicationController
  before_action :set_declutter_comment, only: [:create, :destroy]

  def create
    @declutter_comment = DeclutterComment.new(declutter_comment_params)
    @declutter_comment.declutter_id = @declutter.id
    @declutter_comment.user_id = current_user.id
    @declutter_comment.save
    # render先にjsファイルを指定
    render :declutter_comments
  end

  def destroy
    DeclutterComment.find_by(id: params[:id]).destroy
    # render先にjsファイルを指定
    render :declutter_comments
  end

  private

  def declutter_comment_params
    params.require(:declutter_comment).permit(:comment)
  end
  
  def set_declutter_comment
    @declutter = Declutter.find(params[:declutter_id])
  end

end

app/helpers/declutter_comments_helper.rb
module DeclutterCommentsHelper
end

app/views/declutter_comments/_comments.html.slim
  p
    | コメント件数：
    = @declutter.declutter_comments.count
  - declutter.declutter_comments.each do |declutter_comment|
    .comment_index
      = link_to user_path(declutter_comment.user.id) do
        = attachment_image_tag declutter_comment.user, :profile_image, :fill, 40, 40, fallback: asset_path("no_image.jpg"), size:"40x40", class: "rounded-circle ml-2"
      = declutter_comment.user.name
      | ：
      = time_ago_in_words(declutter_comment.created_at)
      | 前
      - if declutter_comment.user == current_user
        = link_to "", declutter_declutter_comment_path(declutter_comment.declutter,declutter_comment), method: :delete, remote: true, data: {confirm: "本当に削除しますか？"}, class: "btn fas fa-trash"
      p
        = simple_format(h(declutter_comment.comment))

app/views/declutter_comments/_form.html.slim
  = form_with(model:[declutter, declutter_comment]) do |f|
   = f.text_area :comment, placeholder: "コメントをここに"
   br
   = f.submit "送信", class: "btn"

app/views/declutter_comments/declutter_comments.js.erb
$("#comments_area").html("<%= j(render 'declutter_comments/comments', declutter: @declutter) %>");
$("textarea").val('');