config/routes.rb
Rails.application.routes.draw do

  get "relationships/followings"
  get "relationships/followers"
  devise_for :users
  root to: "homes#top"
  get "/homes/about" => "homes#about"
  get "/homes/my_calender" => "homes#my_calender"
  get "/bookmarks" => "bookmarks#index"
  post "/homes/guest_sign_in", to: "homes#new_guest"

  resources :declutters do
    resources :declutter_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    resource :bookmarks, only: [:create, :destroy]
  end

  resources :users, only:[:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord

  belongs_to :user
  belongs_to :declutter

end

app/models/declutter.rb
class Declutter < ApplicationRecord

  belongs_to :user
  has_many :declutter_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  #likesテーブル内に引数で渡されたユーザーが存在しているかどうかを確認
  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  # bookmarksテーブル内に引数で渡されたユーザーが存在しているかどうかを確認
  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  attachment :thing_image

  validates :thing_image, presence:true
  validates :title, presence: true, length: { maximum: 10 }
  validates :caption, presence: true, length: { maximum: 200 }

end

app/models/declutter_comment.rb
class DeclutterComment < ApplicationRecord

  belongs_to :user
  belongs_to :declutter

end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :declutter
  
end

app/models/next_level.rb
class NextLevel < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  # class_name：Userモデルを参照
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :declutters, dependent: :destroy
  has_many :declutter_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  # フォローする・されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロー・フォロワー一覧画面
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローをしているかどうかを確認
  def following?(user)
    followings.include?(user)
  end

  attachment :profile_image
  
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 10}
  validates :introduction, length: { maximum: 50 }

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:create, :destroy]

  def  index
    @bookmarks = Bookmark.where(user_id: current_user.id)
  end

  def create
    @bookmark = @declutter.bookmarks.new(user_id: current_user.id)
    @bookmark.save
    # render先にjsファイルを指定
    render :bookmarks
  end

  def destroy
    @bookmark = @declutter.bookmarks.find_by(user_id: current_user.id)
    @bookmark.destroy
    # render先にjsファイルを指定
    render :bookmarks
  end

  private

  def set_bookmark
    @declutter = Declutter.find(params[:declutter_id])
  end

end

app/controllers/declutters_controller.rb
class DecluttersController < ApplicationController
  before_action :set_declutter, only: [:show, :edit, :destroy, :update]

  def new
    @declutter = Declutter.new
  end

  def create
    @declutter = Declutter.new(declutter_params)
    @declutter.user_id = current_user.id
    if @declutter.save
      user = User.find(current_user.id)

      totalExp = user.exp_point + @declutter.point

      user.exp_point = totalExp
      user.update(exp_point: totalExp)
      # nextlevelモデルから現在のuserレベルよりも1高いレコードを取得
      nextlevel = NextLevel.find_by(level: user.level + 1);
      # 探してきたレコードの閾値よりもユーザーの総経験値が高い場合は、レベル1増やして更新
      if nextlevel.thresold <= user.exp_point
        user.level = user.level + 1
        user.update(level: user.level)
        flash[:levelup]="レベルアップ！"
      end
      flash[:notice]="今日のPoi!を投稿しました"
      redirect_to declutters_path
    else
      render :new
    end
  end

  def index
    @declutters = Declutter.page(params[:page]).reverse_order.per(9)
    # ユーザーのレベルごとのランキングを表示
    @user_ranks = User.order(level: :desc).limit(3).pluck(:id, :level, :name)
    # マイページで自分の投稿のみカレンダーに表示
    @mydeclutters = Declutter.where(user_id: current_user.id)
  end

  def show
    @declutter_comment = DeclutterComment.new
  end

  def edit
    if @declutter.user == current_user
      render :edit
    else
      redirect_to declutters_path
    end
  end

  def destroy
    @declutter.destroy
    redirect_to declutters_path
  end

  def update
    @declutter.update(declutter_params)
    flash[:notice]="投稿を変更しました"
    redirect_to declutter_path(@declutter.id)
  end

  private

  def declutter_params
    params.require(:declutter).permit(:title, :thing_image, :caption, :point, :start_date, :end_date, :user_id)
  end

  def set_declutter
    @declutter = Declutter.find(params[:id])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
  
  def my_calender
  end

  def new_guest
    # emailでユーザーが見つからない場合に作成
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      # ランダムで文字列を生成
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
    sign_in user
    redirect_to declutters_path
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:create, :destroy]

  def create
    @like = @declutter.likes.new(user_id: current_user.id)
    @like.save
    # render先にjsファイルを指定
    render :likes
  end

  def destroy
    @like = @declutter.likes.find_by(user_id: current_user.id)
    @like.destroy
    # render先にjsファイルを指定
    render :likes
  end
  
  private
  
  def set_like
    @declutter = Declutter.find(params[:declutter_id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @declutters = @user.declutters.page(params[:page]).reverse_order.per(6)
  end

  def edit
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice]="プロフィールが更新されました"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # フォームごとのエラーメッセージを表示
  def errors_hash(resource)
    resource.errors.messages.map do |col, errors_array|
      [col, errors_array.map { |error| resource.class.human_attribute_name(col) + error }]
    end.to_h
  end
  
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/declutters_helper.rb
module DecluttersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.slim
.row.mx-auto.footer
  .col-md-12.footer_info
    p.site-info
      | Poi! | みんなで頑張る断捨離共有サイト

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-dark[style="background-color:#434343;"]
  .container-fluid
    a.navbar-brand
      = link_to image_tag(asset_path("logo.jpg"), height:"80px"), root_path, class:"header-logo"

    button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
        -if user_signed_in?
          li.nav-item
            = link_to "Mypage", user_path(current_user.id), class: "nav-link"
          li.nav-item
            = link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link"
          li.nav-item
            = link_to "About", homes_about_path, class: "nav-link"
          li.nav-item
            = link_to "みんなのPoi!", declutters_path, class: "nav-link"
          li.nav-item
            = link_to "今日のPoi!", new_declutter_path, class: "nav-link"
          li.nav-item
            = link_to "Users", users_path, class: "nav-link"
        - else
          li.nav-item
            = link_to "Sign Up", new_user_registration_path, class: "nav-link"
          li.nav-item
            = link_to "Log In", new_user_session_path, class: "nav-link"
          li.nav-item
            = link_to 'ゲストログイン(閲覧用)',homes_guest_sign_in_path, class: "nav-link", method: :post
          li.nav-item
            = link_to "About", homes_about_path, class: "nav-link"

app/views/layouts/_photo_btn.html.slim
/デフォルトのデザインを変更
/#img_field内をクリックしたら#fileもクリックする
#img_field[onclick="$('#file').click()"]
  i.far.fa-images
    |  画像を選択

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Poi
    = csrf_meta_tags
    = csp_meta_tag
    meta[name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
  body[data-turbolinks="false"]
  
    = render 'layouts/header'
                
    - flash.each do |type, msg|
      - type = 'success' if type == 'notice'
      script
        | toastr['
        = type
        | ']('
        = msg
        | ');
        
    = yield
    
    = render 'layouts/footer'